# Generated by Django 5.0.6 on 2026-06-24 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('technique', 'Technique BTP'), ('agricole', 'Agricole / pépinière'), ('conduite_engin', "Conduite d'engin"), ('management', 'Management'), ('administratif', 'Administratif'), ('autre', 'Autre')], default='technique', max_length=20)),
                ('niveau_max', models.PositiveSmallIntegerField(default=5)),
                ('actif', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Compétence',
                'ordering': ['categorie', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI Permanent'), ('cdd', 'CDD'), ('journalier', 'Journalier'), ('moo', 'MOO'), ('stagiaire', 'Stagiaire')], max_length=20)),
                ('poste', models.CharField(blank=True, max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('conge', 'En congé')], default='actif', max_length=20)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('salaire_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taux_journalier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_cnps', models.CharField(blank=True, max_length=30, verbose_name='N° CNPS')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_conge', models.CharField(choices=[('conges_payes', 'Congés payés'), ('maladie', 'Maladie'), ('maternite', 'Maternité / paternité'), ('sans_solde', 'Sans solde'), ('special', 'Spécial (mariage, deuil…)')], default='conges_payes', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=300)),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='demande', max_length=20)),
                ('approuve_par', models.CharField(blank=True, max_length=200)),
                ('approuve_le', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Congé',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=200)),
                ('organisme', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('date_obtention', models.DateField()),
                ('date_expiration', models.DateField(blank=True, help_text='Vide = sans expiration.', null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Certification',
                'ordering': ['-date_obtention'],
            },
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mois', models.DateField(help_text='1er jour du mois concerné (ex: 2026-05-01)')),
                ('brut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('genere', 'Généré'), ('paye', 'Payé')], default='genere', max_length=20)),
                ('paye_le', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'ordering': ['-mois', 'employe__nom'],
                'unique_together': {('employe', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI Permanent'), ('cdd', 'CDD'), ('journalier', 'Journalier'), ('moo', 'MOO'), ('stagiaire', 'Stagiaire')], max_length=20)),
                ('poste', models.CharField(blank=True, max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text='Vide = contrat en cours.', null=True)),
                ('salaire_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taux_journalier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motif_fin', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_contrats', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Historique contrat',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='MissionMoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet_ref', models.CharField(blank=True, max_length=100, verbose_name='Projet / Chantier')),
                ('description', models.CharField(max_length=300)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_forfaitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paye_le', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('employe', models.ForeignKey(limit_choices_to={'type_contrat': 'moo'}, on_delete=django.db.models.deletion.PROTECT, related_name='missions_moo', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Mission MOO',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('mobile', 'Mobile Money')], default='especes', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='N° chèque, référence virement…', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('bulletin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='rh.bulletinpaie')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niveau', models.PositiveSmallIntegerField(default=1)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acquisitions', to='rh.competence')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Compétence employé',
                'ordering': ['competence__libelle'],
                'unique_together': {('employe', 'competence')},
            },
        ),
        migrations.CreateModel(
            name='LigneBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_ligne', models.CharField(choices=[('salaire_base', 'Salaire de base'), ('prime', 'Prime / indemnité'), ('retenue_cnps', 'Cotisation CNPS (part salariale)'), ('retenue_its', 'Impôt sur salaire (ITS)'), ('retenue_autre', 'Autre retenue'), ('net_a_payer', 'Net à payer')], max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='rh.bulletinpaie')),
            ],
            options={
                'verbose_name': 'Ligne de bulletin',
                'ordering': ['bulletin', 'ordre'],
                'unique_together': {('bulletin', 'type_ligne')},
            },
        ),
        migrations.CreateModel(
            name='PresenceJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('heures_travaillees', models.DecimalField(decimal_places=1, default=8, max_digits=4)),
                ('montant_du', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('cloture', 'Clôturé')], default='brouillon', max_length=20)),
                ('projet_ref', models.CharField(blank=True, max_length=100, verbose_name='Projet / Chantier')),
                ('site_ref', models.CharField(blank=True, max_length=100, verbose_name='Site / Lieu')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('paye_le', models.DateField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='rh.employe')),
            ],
            options={
                'verbose_name': 'Présence journalière',
                'ordering': ['-date'],
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
