# Generated by Django 5.0.6 on 2026-06-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
