# Generated by Django 5.0.6 on 2026-06-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_employe_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('especes', 'Espèces'), ('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], default='especes', max_length=20),
        ),
    ]
