# Generated by Django 5.0.6 on 2026-06-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_alter_paiement_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetenueCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI Permanent'), ('cdd', 'CDD'), ('journalier', 'Journalier'), ('moo', 'MOO'), ('stagiaire', 'Stagiaire')], max_length=20, unique=True, verbose_name="Catégorie d'employé")),
                ('taux_cnps_salarial', models.DecimalField(decimal_places=4, default=0.063, help_text='CNPS retraite salarié (ex: 0.0630 pour 6,3%)', max_digits=5)),
                ('plafond_cnps', models.DecimalField(decimal_places=2, default=3375000, help_text='Plafond CNPS retraite = 45 × SMIG', max_digits=12)),
                ('taux_cnps_patronal_retraite', models.DecimalField(decimal_places=4, default=0.077, help_text='CNPS retraite employeur 7,7%', max_digits=5)),
                ('taux_cnps_patronal_pf', models.DecimalField(decimal_places=4, default=0.0575, help_text='Prestations familiales + Maternité 5,75%', max_digits=5)),
                ('taux_cnps_patronal_at', models.DecimalField(decimal_places=4, default=0.02, help_text='Accidents du travail 2%', max_digits=5)),
                ('plafond_pf_at', models.DecimalField(decimal_places=2, default=70000, help_text='Plafond PF + AT', max_digits=12)),
                ('taux_is', models.DecimalField(decimal_places=4, default=0.015, help_text='Impôt sur Salaires IS 1,5%', max_digits=5)),
                ('taux_frais_pro', models.DecimalField(decimal_places=4, default=0.2, help_text='Déduction forfaitaire frais pro 20%', max_digits=5)),
                ('bareme_cn', models.JSONField(default=list, help_text='Barème CN: [{"seuil": 300000, "taux": 0.015, "fixe": 0}, ...]')),
                ('taux_igr', models.DecimalField(decimal_places=4, default=0.1, help_text='Taux IGR 10% appliqué au quotient familial', max_digits=5)),
                ('abattement_igr', models.DecimalField(decimal_places=2, default=15000, help_text='Abattement IGR mensuel', max_digits=12)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Retenue par catégorie',
                'verbose_name_plural': 'Retenues par catégorie',
                'ordering': ['type_contrat'],
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='categorie',
            field=models.CharField(blank=True, choices=[('cadre_iv', 'Cadre IV'), ('cadre_iii', 'Cadre III'), ('cadre_ii', 'Cadre II'), ('cadre_i', 'Cadre I'), ('technicien_ii', 'Technicien II'), ('technicien_i', 'Technicien I'), ('support_ii', 'Support II'), ('support_i', 'Support I'), ('ouvrier', 'Ouvrier')], max_length=20),
        ),
        migrations.AddField(
            model_name='employe',
            name='nb_enfants',
            field=models.PositiveSmallIntegerField(default=0, help_text='Pour calcul IGR'),
        ),
        migrations.AddField(
            model_name='employe',
            name='statut_marital',
            field=models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)')], default='celibataire', max_length=20),
        ),
    ]
