# Generated by Django 5.0.6 on 2026-06-28 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_auto_create_retenues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bulletinpaie',
            index=models.Index(fields=['mois'], name='rh_bulletin_mois_2a2af0_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletinpaie',
            index=models.Index(fields=['statut'], name='rh_bulletin_statut_c2e815_idx'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['type_contrat'], name='rh_employe_type_co_3d0288_idx'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['statut'], name='rh_employe_statut_6eea2c_idx'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['is_deleted'], name='rh_employe_is_dele_36e6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date'], name='rh_paiement_date_a46fab_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['employe'], name='rh_paiement_employe_149cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='presencejournaliere',
            index=models.Index(fields=['date'], name='rh_presence_date_a40404_idx'),
        ),
        migrations.AddIndex(
            model_name='presencejournaliere',
            index=models.Index(fields=['statut'], name='rh_presence_statut_80bceb_idx'),
        ),
        migrations.AddIndex(
            model_name='presencejournaliere',
            index=models.Index(fields=['paye_le'], name='rh_presence_paye_le_166133_idx'),
        ),
        migrations.AddIndex(
            model_name='presencejournaliere',
            index=models.Index(fields=['employe', 'date', 'present'], name='rh_presence_employe_7ad753_idx'),
        ),
    ]
