# Generated by Django 5.0.6 on 2026-06-24 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('type_objectif', models.CharField(choices=[('surface', 'Surface (m²)'), ('volume', 'Volume'), ('unite', 'Unité'), ('lineaire', 'Linéaire (ml)'), ('forfait', 'Forfait')], max_length=20)),
                ('unite_label', models.CharField(max_length=50)),
                ('tarif_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_site', models.CharField(choices=[('chantier', 'Chantier'), ('parcelle', 'Parcelle'), ('pepiniere', 'Pépinière'), ('espace_vert', 'Espace vert'), ('depot', 'Dépôt'), ('autre', 'Autre')], default='chantier', max_length=20)),
                ('localisation', models.CharField(blank=True, max_length=300)),
                ('actif', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(blank=True, limit_choices_to={'statut': 'actif'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_diriges', to='rh.employe')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LogTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('objectif_realise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_heures', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
                ('rendement', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('employe', models.ForeignKey(limit_choices_to={'type_contrat': 'journalier'}, on_delete=django.db.models.deletion.CASCADE, related_name='logs_travail', to='rh.employe')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_travail', to='operations.site')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_travail', to='operations.tachecatalogue')),
            ],
            options={
                'ordering': ['-date', 'employe__nom'],
                'indexes': [models.Index(fields=['date'], name='operations__date_fa6365_idx'), models.Index(fields=['employe', 'date'], name='operations__employe_25cdc0_idx')],
            },
        ),
    ]
