# Generated by Django 5.0.6 on 2026-06-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tachecatalogue',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
