# Generated by Django 5.0.6 on 2026-06-24 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_site_code_alter_tachecatalogue_code'),
        ('rh', '0002_alter_employe_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtravail',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_travail', to='rh.employe'),
        ),
    ]
