# Generated by Django 5.0.6 on 2026-06-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_logtravail_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtravail',
            name='paye_le',
            field=models.DateField(blank=True, null=True),
        ),
    ]
