# Generated by Django 5.0.6 on 2026-06-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_logtravail_paye_le'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtravail',
            name='prime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
