# Generated by Django 5.0.6 on 2026-06-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_logtravail_prime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tachecatalogue',
            name='seuil',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantité minimale non payée (ex: 15 lignes offertes)', max_digits=10),
        ),
    ]
