# Generated by Django 5.0.6 on 2026-06-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_tachecatalogue_seuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtravail',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque')], default='especes', max_length=20),
        ),
    ]
