# Generated by Django 5.0.6 on 2026-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True)),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compteur de code',
            },
        ),
    ]
